// Initial fetch of Vehicle data
export const FETCHING_VEHICLES = 'FETCHING_VEHICLES';
export const FETCH_VEHICLES_SUCCESS = 'FETCH_VEHICLES_SUCCESS';
export const FETCH_VEHICLES_FAILED = 'FETCH_VEHICLES_FAILED';

// Deleting Vehicle
export const DELETING_VEHICLE = 'DELETE_VEHICLE';
export const DELETE_VEHICLE_SUCCESS = 'DELETE_VEHICLE_SUCCESS';
export const DELETE_VEHICLE_FAILED = 'DELETE_VEHICLE_FAILED';

// Adding Vehicle
export const ADDING_VEHICLE = 'ADDING_VEHICLE';
export const ADD_VEHICLE_SUCCESS = 'ADD_VEHICLE_SUCCESS';
export const ADD_VEHICLE_FAILED = 'ADD_VEHICLE_FAILED';

// Updating Vehicle
export const UPDATING_VEHICLE = 'UPDATING_VEHICLE';
export const UPDATE_VEHICLE_SUCCESS = 'UPDATE_VEHICLE_SUCCESS';
export const UPDATE_VEHICLE_FAILED = 'UPDATE_VEHICLE_FAILED';